#'Querying sparql endpoints
#'
#'Function that sends queries on sparql endpoints. It is an alternative to the SPARQL() from the SPARQL package, by allowing retrieving JSON.
#'
#' @param query The SPARQL query.
#' @param url url of the sparql endpoint.
#' @param api_key An api key if needed.
#'  
#' @importFrom jsonlite fromJSON  
#' @importFrom utils URLencode
#' @importFrom purrr map_df
#'   
#' @return  Data table of results generated by the data returned from the SPARQL query
#'
#' @export
#'
#' @references Willem Robert Van Hage et al. SPARQL: SPARQL client, 2013. R package version 1.16.
#'
#' @author  Y. Rivault
#'
#' @examples
#' # Querying SPARQL endpoints :
#' # Retrieving some informations about drugs that are available through db-pedia:
#'  # Drugs and their labels:
#'  query="SELECT DISTINCT * 
#'   WHERE {
#'    ?drug rdf:type dbo:Drug .
#'    ?drug rdfs:label ?label .
#'   }"
#' results <- sparql(query,url="https://dbpedia.org/sparql/")
#' results[1:2,]
#'
#' # Drugs and their drugbank Id:
#' query="SELECT DISTINCT * 
#'  WHERE {
#'   ?drug rdf:type dbo:Drug .
#'  ?drug dbp:drugbank ?db_Id .
#'  }"
#' results <- sparql(query,url="https://dbpedia.org/sparql/")
#' results
#'
#' # Drugs and their ATC Id:
#'query="SELECT DISTINCT ?drug concat(str(?prefix),str(?suffix)) as ?atc 
#' WHERE {
#'  ?drug dbo:atcPrefix ?prefix .
#'  ?drug dbo:atcSuffix ?suffix .
#' }"
#'results <- sparql(query,url="https://dbpedia.org/sparql/")
#'results
#'
# Retrieving some informations about drugs that are available through bio2rdf:
#'
#' query="SELECT DISTINCT *
#'  WHERE {
#'   ?drug <http://bio2rdf.org/kegg_vocabulary:formula> ?formula.
#' }"
#' results <- sparql(query,url="http://bio2rdf.org/sparql")
#' results

sparql <- function(query="",url="",api_key=""){
  
  encoded_query=URLencode(gsub("[[:space:]]+", " ", query),reserved = TRUE)
  
  encoded_url=paste(url,"?query=",encoded_query,sep="")
  
  
  
  if(api_key!=""){
    encoded_url=paste(encoded_url,"&apikey=",api_key,sep="")
  }
  
  cat(paste("Querying ",url,sep=""),"\n",append=T)
  document <- fromJSON(encoded_url)
  
  if(length(document$results$bindings)!=0){
    results=document$results$bindings %>% map_df("value")
  }
  else{results=NULL}
  
  return(results)
}
